-- 005: Add strategic analysis support
-- Run in Supabase SQL Editor

-- 1. Add analysis_framework to implementations (JSON config for analytical methodology)
ALTER TABLE implementations
ADD COLUMN IF NOT EXISTS analysis_framework jsonb DEFAULT NULL;

-- 2. Add strategic_analysis to visit_reports (per-visit markdown analysis)
ALTER TABLE visit_reports
ADD COLUMN IF NOT EXISTS strategic_analysis text DEFAULT NULL;

-- 3. Create consolidated_reports table for cross-visit analysis (backoffice)
CREATE TABLE IF NOT EXISTS consolidated_reports (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    implementation_id text NOT NULL REFERENCES implementations(id),
    title text NOT NULL,
    framework text NOT NULL DEFAULT 'babson_pentagon',
    visit_report_ids uuid[] NOT NULL DEFAULT '{}',
    filters jsonb DEFAULT '{}',
    analysis_markdown text,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    requested_by uuid REFERENCES auth.users(id),
    processing_time_ms integer,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 4. Index for querying consolidated reports
CREATE INDEX IF NOT EXISTS idx_consolidated_reports_impl
ON consolidated_reports(implementation_id, created_at DESC);

-- 5. Set Babson Pentagon framework for Eficacia
UPDATE implementations
SET analysis_framework = '{
  "id": "babson_pentagon",
  "name": "Pentágono de Babson College",
  "description": "Marco de análisis estratégico de retail: Customer, Value Proposition, Revenue Model, Delivery, Ecosystem",
  "model": "claude-sonnet-4-20250514",
  "dimensions": [
    {
      "id": "customer",
      "label": "Cliente (Customer)",
      "prompt": "Identifica los segmentos de cliente que el punto de venta está diseñado para atender. Para cada segmento describe: motivación de compra, evidencia visible en las fotos, comportamiento esperado, y relevancia estratégica. Busca misiones de compra diferenciadas (conveniencia, reposición, bienestar, especializado)."
    },
    {
      "id": "value_proposition",
      "label": "Propuesta de Valor (Value Proposition)",
      "prompt": "Sintetiza la propuesta de valor implícita del punto de venta. Analiza en niveles: ¿qué ofrece a nivel funcional (productos), emocional (experiencia), y aspiracional (posicionamiento)? Evalúa si la propuesta está claramente articulada o si es implícita. Identifica fortalezas y brechas."
    },
    {
      "id": "revenue_model",
      "label": "Captura de Valor (Revenue Model)",
      "prompt": "Analiza el modelo de ingresos visible. Identifica los motores de revenue: tráfico (productos de alta rotación), ticket incremental (upsell/cross-sell), margen premium (categorías de alto margen), y promociones estructuradas. Si hay calendario promocional o sistema de descuentos, analízalo."
    },
    {
      "id": "delivery",
      "label": "Arquitectura del Negocio (Delivery)",
      "prompt": "Evalúa la arquitectura operativa del punto de venta: layout y zonificación de categorías, merchandising y señalización, ubicación estratégica de refrigeración/exhibidores, flujo del cliente. Identifica fortalezas operativas y debilidades (exceso de SKU, falta de asesoría, problemas de navegación)."
    },
    {
      "id": "ecosystem",
      "label": "Ecosistema (Partners)",
      "prompt": "Mapea el ecosistema de marcas y partners presentes. Agrupa por categoría (dermocosmética, wellness, consumo masivo, etc.). Evalúa qué aporta cada grupo al modelo (credibilidad, tráfico, margen). Identifica dependencias y oportunidades de integración."
    }
  ],
  "closing_prompt": "Genera un Gold Insight estratégico: ¿cuál es el modelo competitivo real de este punto de venta? ¿Con quién compite realmente (no solo competidores directos)? ¿Qué transición estratégica está ocurriendo? Formula una hipótesis estratégica en el estilo de Babson. Luego lista las 3 oportunidades estratégicas más importantes con acciones concretas.",
  "consolidation_prompt": "Eres un consultor senior de retail y trade marketing. Tienes los análisis individuales de {visit_count} visitas a puntos de venta realizadas por el equipo de campo. Tu trabajo es consolidar estos análisis en un reporte ejecutivo estratégico usando el Pentágono de Babson. Para cada dimensión, identifica: patrones comunes, variaciones significativas entre puntos, benchmarks internos (mejor vs peor). Genera insights accionables para el equipo comercial. Incluye un Executive Summary al inicio y un plan de acción priorizado al final."
}'::jsonb
WHERE id = 'eficacia';

COMMENT ON COLUMN implementations.analysis_framework IS 'JSON config for strategic analysis methodology (e.g., Babson Pentagon). NULL = no analysis.';
COMMENT ON COLUMN visit_reports.strategic_analysis IS 'Per-visit strategic analysis markdown, generated by Phase 3 analyzer.';
